### ISSUE TITLE
released tag v1.12.2 doesn't appear to exist on the main branch?

### ISSUE THREAD

**Issue by dnwe** [prometheus/client_golang#1070]
Whilst looking at a race condition on v1.12.2 I happened to notice that the release tag v1.12.2 doesn't exist on the main branch and appears to live on a release-1.12 branch that has diverged:
https://github.com/prometheus/client_golang/tree/v1.12.2

Is that intentional?

**Comment by kakkoyun** [comment]
Yes, it is intentional. We create a release branch and tagged the versions there if we need to cherry-pick commits from the main branch. 

https://github.com/prometheus/prometheus/blob/main/RELEASE.md#branch-management-and-versioning-strategy

All the relevant changes should be on the main as well. Do you see any missing changes on the main?

**Comment by beorn7** [comment]
It's ever trickier, see #1083.
