### ISSUE TITLE
Installing examples is not working anymore

### ISSUE THREAD

**Issue by itsmylife** [prometheus/client_golang#1119]
I am trying to install the examples with the command below:
```
$ go install github.com/prometheus/client_golang/examples/random@latest
```

but I am getting the following error:
```
go: github.com/prometheus/client_golang/examples/random@latest (in github.com/prometheus/client_golang@v1.13.0):
	The go.mod file for the module providing named packages contains one or
	more exclude directives. It must not contain directives that would cause
	it to be interpreted differently than if it were the main module.
```

This was working with the previous version:
```
go install github.com/prometheus/client_golang/examples/random@v1.12.2
```

I assume the changes introduced here https://github.com/prometheus/client_golang/pull/1062 are the reason. Especially this line: 
https://github.com/prometheus/client_golang/blob/main/go.mod#L31

My Go Version: 
```
go version go1.18.1 darwin/arm64
```

**Comment by beorn7** [comment]
Maybe we need the examples to use their own `go.mod`? But that might lead to weird situations…

Or we can reconsider the `exclude` directive? IIRC it was only added to silence buggy security scanners (that would be confused by the dependency resolution method of Go Modules when faced with circular dependencies).

**Comment by kakkoyun** [comment]
Both the strategies make sense. 
With the new Go workspace features having different modules in a project should be rather easier. 
Also, we might already have deprecated the need for the exclude, if I'm not mistaken we have bumped the minimum required Go version since then. And the issue was related to the older Go version. (I might misremembering things).

**Comment by Dean-Coakley** [comment]
I've started taking a look at this issue to see if I can help.

1. I'm pretty new to workspaces. Should `go.work` be committed, or should I add an entry to `.gitignore`?
2. After I've made my changes how do I validate that I've solved the original issue?

**Comment by minseok-oh** [comment]
It seems like the error mentioned in the comment below is related to the issue above. 
Is this `exclude` directive intentional and something that cannot be modified?
If this was intentional, could you please provide some context on why the `exclude` directive was added?
@kakkoyun @beorn7 

https://github.com/prometheus/client_golang/issues/1169#issuecomment-3764926353
