### ISSUE TITLE
NativeHistogramBucketFactor not match right bucket

### ISSUE THREAD

**Issue by songjiayang** [prometheus/client_golang#1159]
I use main branch code with commit hash 5f202eefdb5dcb9b5b26d4d7c3351d1e5a0d9bc7 to test NativeHistogram feature，I set the NativeHistogramBucketFactor  to `math.Exp2(0.5)`, I really want use  `Schema 1` https://github.com/prometheus/client_golang/blob/main/prometheus/histogram.go#L44 buckets, but when I use Prometheus to collect data, find it use `Schema 2` buckets.

When I change the NativeHistogramBucketFactor   to `math.Exp2(0.5001)`, it use `Schema 1` buckets.

**Comment by beorn7** [comment]
That's probably a floating point precision issue. `math.Exp2(0.5)` is an irrational number and cannot be expressed precisely as a floating point number. Since NativeHistogramBucketFactor provides an upper bound for the actually used factor, the code chooses the schema with a higher resolution, presumably because the imprecise floating point comparison lets your provided factor appear slightly smaller than the factor used by schema 1.

To reliably pick schema 1, I recommend to provide a factor that is clearly larger than `math.Exp2(0.5)`, e.g. 1.5.

Note that users should normally not think about the schema picked behind the scenes. They should simply say "I want an accuracy at least this high".
