### ISSUE TITLE
Inconsistent signature methods

### ISSUE THREAD

**Issue by fabxc** [prometheus/client_golang#122]
Currently we have different methods to extract signatures from labels.

`func LabelsToSignature(labels map[string]string) uint64`
`func SignatureForLabels(m Metric, labels LabelNames) uint64`
`func SignatureWithoutLabels(m Metric, labels map[LabelName]struct{}) uint64`

Those should all accept `model.LabelSet`. I can easily convert from `Metric` to `LabelSet` but have to do a full copy to go from `Metric` or `LabelSet` to `map[string]string`.
`LabelsToSignature` is used in the `text` parser. We are going out of our way to use all our custom types everywhere. There we are doing the inverse. Is this for a particular reason?

For `SignatureWithoutLabels`:

In the general case callers will have a slice of labels rather than a `map[string]struct{}` set. The implementation transforms the map into a slice again anyway. The method works just fine, even if there were duplicates.
I see no good reason to enforce this. Callers should make sure the labels are unique (e.g., ensured by the parser).

I'd also consider making the labelname slices variadic.

Not super urgent but I feel like those exported functions were created on demand of local internal uses and from the outside they seem a bit arbitrary.

**Comment by beorn7** [comment]
*deep_breath*

So, this is actually a mess, kind of for historical reasons, but those reasons are..., well, kind of reasonable.

The root of all evil is that it was decided to use the named types `Metric` and `LabelSet` (and many more) in the server code (for a number of reasons). But in the code of the exposition library, those named types are not to be used, presumably because a writer of client instrumentation doesn't care about the abstractions and methods the server has around metrics and labels. So in the exposition library, label values and names are just strings, and label "sets" are map[string]string, and a `prometheus.Metric` is actually something very much different from a `model.Metric` in the server code.

I put all the fingerprinting functions into signature.go, to have all that related logic in one place. However, in that file, we have a collision between the server world and the exposition library world.

To keep `LabelSet` and such out of the exposition library, we need signature functions that act an map[string]string.

The `text` package is also one of the packages that should not use the custom "server" types.

WRT SignatureWithoutLabels: This function is used only once in our own codebase, and the excluded labels are a "constant" value (`var` but not `const` in Go just because it is a map). See https://github.com/prometheus/prometheus/blob/2579606e77121f8021e123056fb3fdd06790c1e6/promql/quantile.go#L27 . The implementation does _not_ transform the labels map into a slice but makes use of the map as a set (to achieve constant runtime).
