### ISSUE TITLE
The latest version of the package provides methods that are not compatible with version 1.12

### ISSUE THREAD

**Issue by xmh1011** [prometheus/client_golang#1488]
In v1.12.0, There are some methods about `Desc` in file `prometheus/desc.go` provided, such as:
```
func (d *Desc) Name() string {
	return d.fqName
}

func (d *Desc) Help() string {
	return d.help
}

func (d *Desc) ConstLabels() []*dto.LabelPair {
	return d.constLabelPairs
}

func (d *Desc) VariableLabels() []string {
	return d.variableLabels
}

func (d *Desc) Err() error {
	return d.err
}
```
Now, they are not supported in v1.19.0. What should I do if I need to get `desc.Name()`?

**Comment by kakkoyun** [comment]
Thanks for reporting. However, `1.12` is a very old version of Go, and the Go core team does not even support it. The last three major versions are supported officially. The same policy applies to client_golang as well.

Since Go is forward-compatible, I would suggest you upgrade your Go compiler version.
