### ISSUE TITLE
darwin: Building with CGO produces warning 

### ISSUE THREAD

**Issue by bwplotka** [prometheus/client_golang#1660]
```
# github.com/prometheus/client_golang/prometheus
In file included from process_collector_cgo_darwin.c:21:
/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/mach/shared_memory_server.h:48:2: warning: "<mach/shared_memory_server.h> is deprecated.  Please use <mach/shared_region.h> instead." [-W#warnings]
```

This is on the latest client_golang (main) version, likely after https://github.com/prometheus/client_golang/pull/1616

Does not look serious, but something to fix cc @mharbison72

**Comment by mharbison72** [comment]
Unfortunately, they don't provide a replacement header with a couple of constants that are used, and I'm not aware of any `#pragma` style directives that can be put into the code to suppress a `#warning`.  The Apple repos have now been updated with the new OS release from last month, and nothing has changed in this area.  That leaves us with a couple of hacky options:

1) Copy the constants from the header, and don't include the header itself
1) See if there's some `CFLAGS` option to suppress `#warning` directives
1) Drop the adjustment of the value that's being done

The first is probably the easiest, and probably my preference (and add a `#warning` if the architecture isn't supported, since the constants are arch specific?).

The second seems too broad.

The third is a possibility, because as mentioned in the commit comment and the code, I've never seen the adjustment amount be non-zero.  But if there's a case that could happen, we wouldn't report the same value as `ps(1)`.

What do you think?
