### ISSUE TITLE
Handler should log errors, not only return it

### ISSUE THREAD

**Issue by discordianfish** [prometheus/client_golang#268]
Hi,

I just realize that we don't log fatal errors in the handler. If a Collector for example sends duplicated metrics down the channel, the Handler returns a 500 and error message to the client, but nothing gets logged.
I can (probably?) implement my own handler, but I'd argue we should log this by default.

**Comment by beorn7** [comment]
It is already implemented, but you have to configure logging, see https://godoc.org/github.com/prometheus/client_golang/prometheus/promhttp#HandlerOpts

I find it problematic to log by default in a library because I cannot guess what logging model the user of my library is following.

**Comment by discordianfish** [comment]
Ah, didn't know!

Regarding default logging.. In general I agree that a library shouldn't log, but maybe a http handler like this is an exception. I'd say the general assumption is that a http services logs internal errors but given how high level the client_golang interface is (in the simplest case), people won't think about logging. You'll find evidence for that in all of our exporters, except snmp.

We could also force people to specify a logger or error handler, might be a better option than logging to the default logger.

**Comment by discordianfish** [comment]
Actually the snmp exporter doesn't set up logging either.

**Comment by beorn7** [comment]
Yes, I am very aware of the dilemma here. The whole default setting is optimized for zero config, and so far, I still think that returning 5xx with the error is the best default behavior. I really don't want to force users to configure anything, especially because many use cases (like direct instrumentation) will almost never need to log anything.

More involved Go programs will probably avoid the global default registry and handler anyway (given the general dislike for global state in the Go community), and then people will think about logging anyway. Or in other words: The user who is sufficiently naive to not think about logging is probably best served with the zero config default settings anyway.

Contrary evidence in existing code is not very meaningful as the custom HTTP handler was only introduced quite recently.

As I'm pretty convinced the current behavior shouldn't be changed (this library keeps my brain spinning ever since early 2014, so I have iterated through quite a few variants…), I'm closing this issue. If you feel strongly it should be reconsidered at a later time, please re-open.

**Comment by discordianfish** [comment]
No problem, was just surprised about the behavior. But fair enough, probably due to our exports being quite 'legacy' from their client usage.
