### ISSUE TITLE
Check validity of label values.

### ISSUE THREAD

**Issue by beorn7** [prometheus/client_golang#274]
Label values can be any UTF-8 string. However, not any arbitrary byte sequence is a valid UTF-8 string. (FF bytes are always illegal, as an example.)

The Prometheus server validates label values upon ingestion. Thus, the client library should prevent invalid label from being exposed.

https://github.com/prometheus/snmp_exporter/issues/117 exposed this problem.

**Comment by beorn7** [comment]
https://github.com/prometheus/snmp_exporter/issues/116 . too.

**Comment by juliusv** [comment]
A user on IRC just ran into this (via different sources pushing metrics to the StatsD exporter).

**Comment by juliusv** [comment]
Oops, wrong issue, deleting my comments and pasting on the right one.

**Comment by marco-jantke** [comment]
Hi @beorn7,

I started to have a look at this issue, because we have a related issue in [Traefik](https://github.com/containous/traefik/issues/1821). I did not contribute to the client_golang library so far and I would like to hear your opinion before going forwards and opening a PR.

I see that there are a couple of approaches to implement the validation. First I would like to understand what should be done in general with invalid input, should we try to sanitize with best effort to utf-8 or should we just completely throw away the Metric sample? I think that the second approach is better, because there also could be inputs that can not be sanitized properly, e.g. when they consist of only invalid chars for utf8 and would therefore be sanitized to an empty string.

Another point is about when the validation should happen. I saw basically two options while looking into the code:

1. Validate the data when `Get`_ing_ the metric from a Vector. Basically somewhere inside of `hashLabels` and `hashLabelValues`. There similar to the cardinality check we could return an error. 
2. Validate the data when `Gather`_ing_ the metric. It seems the validation could be done in: `checkMetricConsistency`.

Both options have their tradeoffs. For option nr 1 there are code paths where returning an error from `hashLabels` leads to a panic. At least in the Traefik project I think this is not desirable, as a user experienced a problem where a client sent invalid utf-8 in the request method. The second option has the disatvantage that it is a "silent error". WDYT about the better approach here or do you have some more ideas on how to go?

Regardless of the fix here I would be interested in your opinion whether clients should always do validation of data before passing it to this client library or if it should be the responsibility to handle any invalid data and therefore it is safe to use out of the box?

**Comment by beorn7** [comment]
Thanks for your interest. It would be great if you could tackle this issue.

As you say, I think we should not try to sanitize but instead but instead error out. Errors should be raised as soon as possible, i.e. `GetMetricWith` or `GetMetricWithLabelValues` should directly return an error if the provided label values are not valid UTF-8 strings. `With` and `WithLabelValues` should thus panic in that situation.

Also that check needs `NewConstMetric`, `NewConstSummary`, and `NewConstHistogram` (with the error returned) and `NewDesc` (with the error recorded in the `Desc`).

The `Metric` type even mentions the topic in its doc comment: “While populating dto.Metric, it is the responsibility of the implementation to ensure validity of the Metric protobuf (like valid UTF-8 strings or syntactically valid metric and label names).”

However, since we cannot guarantee that implementations stick to the contract, we _also_ need to check things upon `Gather`ing (as a `Gatherer` implementation must never return inconsistent and/or invalid metrics). I agree that the right place is `checkMetricConsistency`.

Hope that makes sense. Looking forward to your PR.

**Comment by marco-jantke** [comment]
That description makes sense to me, thanks a lot for the elaboration. It can take a week or two until I will find time to create the PR but it is on my list now :)
