### ISSUE TITLE
histogram.Write creates invalid result when racing with observe

### ISSUE THREAD

**Issue by lmb** [prometheus/client_golang#275]
Seems like the library will create invalid histograms when histogram.Observe races with histogram.Write.

```
$ go build && ./promrace
found race
sample_count: 9590
sample_sum: 18220.999999999192
bucket: <
  cumulative_count: 0
  upper_bound: 1
>
bucket: <
  cumulative_count: 9591
  upper_bound: 2
>
```

Note that sample_count is lower than cumulative_count of the highest bucket.

See https://gist.github.com/lmb/3caaeb79efc6d6e0d2bdde8a4865e636 to reproduce. It's possible to fix this by changing the order of the atomic adds, but that will then overstate the +Inf bucket by one in some cases.

**Comment by beorn7** [comment]
Yeah, this is kind of by design. If we wanted to update all three, `sample_count`, `sample_sum`, and the respective bucket, we needed way more sophisticated locking. Which might be costly in terms of performance.

By incrementing the `sample_count` first, as you considered, we would at least make sure no bucket has a higher count than `sample_count`. Results look more consistent then, but are still incorrect.

I have some vague ideas with buffer swaps that could get proper atomicity of observation without excessive locking cost... will continue to think about it.

**Comment by lmb** [comment]
Sorry for not replying earlier. To me it seems like changing the behaviour would be desirable, since then we at least generate histograms which are valid (but still not correct).

**Comment by beorn7** [comment]
Yes, this is on the 0.9 milestone.
