### ISSUE TITLE
is it possible to have nil as default value as opposed to 0 ?

### ISSUE THREAD

**Issue by medyagh** [prometheus/client_golang#283]
is it possible that if a metric is 0, to return nil ? for my metric I rather missing data than 0.

**Comment by brian-brazil** [comment]
That's not really possible, and it's not easy to deal with missing data on the Prometheus end.

**Comment by beorn7** [comment]
@medyagh I don't quite understand your question right now? Where exactly do you want to return nil? A sample value is a float64. It cannot be nil. As @brian-brazil says, you generally don't want to remove a metric altogether.

If you just want to signal some kind of "invalid" value, how about using NaN? A Gauge can be set to it, and we use NaN at several places in the Prometheus data model.

**Comment by beorn7** [comment]
No response in a while. Closing.

**Comment by medyagh** [comment]
@beorn7 Using NaN is reasonable. any sample of using NaN?

**Comment by brian-brazil** [comment]
Don't use NaN unless you've a mathematical justification for doing so, as NaNs propagate.

**Comment by beorn7** [comment]
@medyagh I suggest to discuss your use case on the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users") rather than here in a GitHub issue. On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.
