### ISSUE TITLE
Missing dependencies and no installation instructions in readme

### ISSUE THREAD

**Issue by let4be** [prometheus/client_golang#312]
I made go get `github.com/prometheus/client_golang`

When I try to compile an example I get
```
../../../../prometheus/client_golang/prometheus/summary.go:23:2: cannot find package "github.com/beorn7/perks/quantile" in any of:
	/home/dev/go/src/github.com/beorn7/perks/quantile (from $GOROOT)
	/home/dev/projects/go/src/github.com/beorn7/perks/quantile (from $GOPATH)
../../../../prometheus/client_golang/prometheus/desc.go:22:2: cannot find package "github.com/golang/protobuf/proto" in any of:
	/home/dev/go/src/github.com/golang/protobuf/proto (from $GOROOT)
	/home/dev/projects/go/src/github.com/golang/protobuf/proto (from $GOPATH)
../../../../prometheus/client_golang/prometheus/desc.go:25:2: cannot find package "github.com/prometheus/client_model/go" in any of:
	/home/dev/go/src/github.com/prometheus/client_model/go (from $GOROOT)
	/home/dev/projects/go/src/github.com/prometheus/client_model/go (from $GOPATH)
../../../../prometheus/client_golang/prometheus/http.go:29:2: cannot find package "github.com/prometheus/common/expfmt" in any of:
	/home/dev/go/src/github.com/prometheus/common/expfmt (from $GOROOT)
	/home/dev/projects/go/src/github.com/prometheus/common/expfmt (from $GOPATH)
../../../../prometheus/client_golang/prometheus/desc.go:23:2: cannot find package "github.com/prometheus/common/model" in any of:
	/home/dev/go/src/github.com/prometheus/common/model (from $GOROOT)
	/home/dev/projects/go/src/github.com/prometheus/common/model (from $GOPATH)
../../../../prometheus/client_golang/prometheus/process_collector.go:16:8: cannot find package "github.com/prometheus/procfs" in any of:
	/home/dev/go/src/github.com/prometheus/procfs (from $GOROOT)
	/home/dev/projects/go/src/github.com/prometheus/procfs (from $GOPATH)
```

**Comment by beorn7** [comment]
That's because you `go get` just the root dir, but not the actual example.

Do `go get hub.com/prometheus/client_golang/examples/random` or `go get github.com/prometheus/client_golang/examples/simple`. That's common Go practice and as such not documented.

In general, it makes more sense to ask questions like this on the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users) rather than in a GitHub issue. On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.

**Comment by let4be** [comment]
Why do I need to `go get` some weird example in addition to the library itself when I just want to use the library?
Consider user downloading a library and wants to use it from his project, he'd also get missing dependencies
Am I wrong here?

**Comment by beorn7** [comment]
If you don't want to use the example, you don't have to get it.
Using the library works as libraries in Go work. Dependencies are not included.

If you would like to ask more questions, please do so on the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users) rather than in a GitHub issue. On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.
