### ISSUE TITLE
Does it support tcp mode? 

### ISSUE THREAD

**Issue by penhauer-xiao** [prometheus/client_golang#313]
Also have detailed documentation on client_go?   Or about exporter?

**Comment by brian-brazil** [comment]
In general, it makes more sense to ask questions like this on the prometheus-users mailing list at https://groups.google.com/forum/#!aboutgroup/prometheus-users rather than in a GitHub issue. On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.

**Comment by penhauer-xiao** [comment]
Sorry, I forgot, thank you.
