### ISSUE TITLE
Expose Desc fields

### ISSUE THREAD

**Issue by AlekSi** [prometheus/client_golang#322]
I would like to have read-only access to `Desc` fields, specifically, `fqName`. Right now we use [an ugly hack in tests](https://github.com/percona/proxysql_exporter/blob/ba3b3b721fd31e549788172b73e7921395a16fbb/exporter_test.go#L38) to get it. Methods for `help`, `constLabelPairs` and `variableLabels` can also be provided for convenience.

I can send a PR if you are ok with that.

Related to #222.

**Comment by AlekSi** [comment]
@beorn7 What do you think?

**Comment by beorn7** [comment]
The way Desc work will change fundamentally with #222. Tests in code using client_golang (in contrast to tests that test client_golang itself) must not depend in implementation details of client_golang. Simply making internal fields exported in Desc would only allow users to depend on all those internal implementation details (that are about to change anyway).

I would like to ask you to wait for the outcome of #58 and then #230. Right now, exposing Desc fields would be a step in the wrong direction.

**Comment by AlekSi** [comment]
> Right now, exposing Desc fields would be a step in the wrong direction.

How can I help you to make a step in the right direction then? I just hit this issue again and would like to remove that hack.

**Comment by beorn7** [comment]
The required change will go along with a lot of breaking changes and is therefore scheduled for v0.10, see milestones.
The plan is to first get v0.9 out of the door so that we have all the low hanging fruit we can get without breaking changes.
You could check out if you can help with any of the 11 remaining v0.9 issues. But most of them require a lot of context. Unless you are a domain expert already in one, it will probably require more time to transfer context to you and review the code than doing it myself.
(And yes, I'm planning to work on this soon.)
