### ISSUE TITLE
How are dependencies pinned?

### ISSUE THREAD

**Issue by pratikmallya** [prometheus/client_golang#353]
Hi, how are the dependencies for the client locked in? I'm using the client code in my app to talk to prometheus, and I get this error when trying to build my app (I use glide):

```
$ go build
# .../vendor/github.com/prometheus/client_golang/prometheus
../vendor/github.com/prometheus/client_golang/prometheus/desc.go:88: undefined: model.IsValidMetricName
../vendor/github.com/prometheus/client_golang/prometheus/labels.go:56: model.LabelName(l).IsValid undefined (type model.LabelName has no field or method IsValid)

```

How can I get the versions of dependencies (specifically the `model` project), for me to be able to build my application?

For reference, I use glide for dependency management, and have pinned my the client to `v0.8`

**Comment by beorn7** [comment]
> how are the dependencies for the client locked in?

As it is the current practice to not vendor dependencies of libraries within the library repo, they simply aren't.

We try to keep client_golang working if you build against the current master of its dependencies. In your case, it looks like you have vendored an outdated version of the `model` package (to be found [here](https://github.com/prometheus/common/tree/master/model)).

In different news, it makes more sense to ask questions like this on the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users) rather than in a GitHub issue. On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.
