### ISSUE TITLE
Add a metric dynamically?

### ISSUE THREAD

**Issue by snaix** [prometheus/client_golang#364]
Hi
I recently started evaluating prometheus and trying to write a exporter in my project.
After reading some examples, I'm not sure if there is a way to create a metric dynamically.
In these example, all metric is predefined.
For example, my project will export a metric like "how many rows in a table", 
what the table name is created manually or dynamically by programs.
I have to create a metric "%tablename%_rows" after launching prometheus exproter .
It seems that although I can get the %tablename% by programing, I can't add it in exproter as metric?
So is there any way to do it? Thanks.

**Comment by andrestc** [comment]
Based on your example, I think labels are what you are looking for. Instead of having metrics called "%tablename%_rows", you would end up with a single metric "rows" with a label for the table names:

```
rows{name="table1"}
rows{name="table2"}
```

The code [here](https://github.com/prometheus/client_golang/blob/master/examples/random/main.go) is an example where "service" is used as label for the rpcDurations metric. Every time a value is observed, this value has to be associated with a service (in the example code services are "uniform", "normal" and "exponential").

**Comment by beorn7** [comment]
Yeah, definitely use a label for the table name.

To create metrics dynamically, have a look at https://godoc.org/github.com/prometheus/client_golang/prometheus#NewConstMetric and similar.

If you need more clarification, please ask on the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users) rather than in a GitHub issue. On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.

**Comment by snaix** [comment]
Thank you, OK, I will post question to users mailing list.
