### ISSUE TITLE
Release a new stable version to not have go dep default to 0.8.0

### ISSUE THREAD

**Issue by dlespiau** [prometheus/client_golang#375]
By default, `go dep` will take the latest stable version released. For `client_golang` this means it will lock the 0.8.0 version from 2016-08-17. It seems a sub-optimal default and was causing our golang services to be missing interesting metrics and bug fixes.

The work around is to pin client_golang to the master branch in `Gopkg.toml` with:
```
[[constraint]]
  name = "github.com/prometheus/client_golang"
  branch = "master
```

The lock file will lock client_golang to a specific hash for reproducible builds until go dep is instructed to bump the verison.

**Comment by beorn7** [comment]
Dup of #344 . There is this [tag](https://github.com/prometheus/client_golang/releases/tag/v0.9.0-pre1) if you want to have a tag that's more recent. I'll create a v0.9.0-pre2 tag soon.

dep is an upcoming tool much younger than our release planning here. Rather than adjusting our release planning to the next tool currently leading the pack in Go dependency management, I'll focus on getting to 1.0.0 ASAP.

**Comment by beorn7** [comment]
Also of note:
- Go dep is still officially experimental.
- We aim to keep the tip of the master branch always stable. If you are interested in getting the newest fixes and features, set `branch="master"` in your GOPKG.TOML.
- semver semantics only really gets traction from 1.0.0 upwards. Once this repo has reached that state, you can use a semver version config in your GOPKG.TOML. But right now, this repo is at least as experimental as Go dep itself.
