### ISSUE TITLE
Add 404 to general metrics and exclude /metrics

### ISSUE THREAD

**Issue by IgorN** [prometheus/client_golang#388]
Hi!

Some simple question:
1. How can I add HTTP 404 code to general metrics for all routers?
promhttp_metric_handler_requests_total{code="200"} 1
promhttp_metric_handler_requests_total{code="500"} 0
promhttp_metric_handler_requests_total{code="503"} 0
promhttp_metric_handler_requests_total{code="404"} 0 - I'd like to see this

2. How can I exclude /metrics router from metrics?

promhttp_metric_handler_requests_total{code="200"} 1 - here will be wrong value if someone regularly ask  /metrics host

**Comment by beorn7** [comment]
It makes more sense to ask questions like this on the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users) rather than in a GitHub issue. On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.
