### ISSUE TITLE
Simple single Query using API

### ISSUE THREAD

**Issue by AlexandrSemak** [prometheus/client_golang#389]
HI All,

Could you get example for initializing pormetheus client and simple query metric using API.

Thank you for advance

**Comment by brian-brazil** [comment]
It makes more sense to ask questions like this on the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users) rather than in a GitHub issue. On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.
