### ISSUE TITLE
Reset() functions for Histogram And Summary

### ISSUE THREAD

**Issue by yasharya1984** [prometheus/client_golang#392]
I do not see any Reset function for Histogram.  We want to observe the Histogram and Summary for a duration (say 10 seconds) then wants to start fresh with same members which are already registered.  We do not want to create new Histogram every ten seconds. 
What is the best way to do the same ?

Using client_golang in my application.

**Comment by beorn7** [comment]
This is not how Prometheus works. Prometheus is a time-series based monitoring system. It regularly scrapes the counters of a histogram, which then allows PromQL queries to calculate quantiles and such for arbitrary time ranges. See https://prometheus.io/docs/prometheus/latest/querying/functions/#histogram_quantile() and https://prometheus.io/docs/practices/histograms/ .

For summaries, you can specify the age after which observations become irrelevant, in the `SummaryOpts` https://godoc.org/github.com/prometheus/client_golang/prometheus#SummaryOpts , see `MaxAge`. You could set it to 10s and the `AgeBuckets` to 1 to get the behavior you wanted above. However, I don't think that those settings are particularly useful in practice.

If you have more questions about this, it makes more sense to ask them on the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users) rather than in a GitHub issue. On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.
