### ISSUE TITLE
Create API client for Alert Manager

### ISSUE THREAD

**Issue by bobmshannon** [prometheus/client_golang#399]
We currently have an API client written for the V1 HTTP API exposed by Prometheus but not Alert Manager. However, https://github.com/prometheus/alertmanager/issues/511 suggests that the API may not yet be stable enough to do -- so perhaps that may need to be addressed first.

Relates to https://github.com/prometheus/alertmanager/pull/1278

**Comment by simonpasquier** [comment]
This has been discussed previously and the consensus (see https://github.com/prometheus/client_golang/pull/333#issuecomment-359249862) was indeed to have the client code in the AlertManager project rather than in client_golang.

There's https://github.com/prometheus/alertmanager/pull/1314 being worked on. Once this is merged, you should be able to use the `github.com/prometheus/alertmanager/client` package as the AlertManager API client.

**Comment by beorn7** [comment]
Yes, for now, the way to go (for Go ;) is to have the Alertmanager API client in the Alertmanager repo
