### ISSUE TITLE
[feature request] Provide ability to update easily GaugeVec on collection time only

### ISSUE THREAD

**Issue by baryluk** [prometheus/client_golang#410]
Hi,

I do have a map of gauges (using `NewGaugeVec`) with a additional label (dimension) `channel_id`.

I would like to be able to do a single pass over my own app data structures and provide new values for gauges in this vector, as well possibly automatically remove the ones that I do not have in the data structure anymore

For example:

```go
b := promauto.NewGaugeVecObserver(GaugeOpts(Name:"balance"), []string{"channel_id"})
b.OnUpdate(func(m* prometheus.Map) error {
  graph := server.Channels()
  for channel := graph {
    m.WithLabelValues(channel.ChannelID()).Set(channel.Ballance())
    // or just b.Set, but that would be not atomic, and could have a bit more inefficiencies
  }
  return nil
}, /* optional part */ OnUpdateOpts{RemoveMissing: true, CacheFor: 60.0, Timeout:...})
```

(returning just a map could be another option, but then the type of the function would be very complex).

The function passed to `OnUpdate` will be executed ONCE when `/metrics` is accessed, and will provide values for all labels at once and up to date. Only other way of doing this today is to either adjust gauges everytime i modify `server.Channels()` data structures (which might be in multiple places), or by having separate background go routine that periodically updates `"balance"` gauge vector.

As an additional wish, ability to cache gauges as they are for configurable time, would be useful. I.e. Do not call `OnUpdate` again if one was called just 5 second ago, i.e. if one believes that computation of gauges is expensive, or one monitors same node from multiple redundant Prometheus nodes.

Timeout could be a feature to continue executing `OnUpdate `function, in background, but if it reaches timeout consider old values still valid and return back to prometheus monitoring node immediately without waiting anymore.

PS. `OnCollection` instead `OnUpdate` could be better name.

**Comment by beorn7** [comment]
The way to do this is to implement your own `prometheus.Collector`: https://godoc.org/github.com/prometheus/client_golang/prometheus#Collector

It's `Collect` method is essentially your `OnUpdate`. You would then use the `NewConst...` group of constructor functions to create `Metric` instances to collect in `Collect`.

For more information, see
https://godoc.org/github.com/prometheus/client_golang/prometheus#hdr-Custom_Collectors_and_constant_Metrics

Or watch https://youtu.be/HkEZ1LJ7kzQ?t=23m55s 

If you have more questions, it makes more sense to ask them on the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users) rather than in a GitHub issue. On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.

**Comment by baryluk** [comment]
I know it can be done by creating custom Collector. I am asking to provide a factory function that creates them to the specification I described. It also make sense to provide such functionality as we do have *Func suffixed methods to create gauges and counters, but not for vectors of them.

**Comment by beorn7** [comment]
The signature and general handling of such functions would be quite clunky. That's why I deliberately only provided those "single value" functions.
If you have a special use case where it would actually be handier to have those functions, you could still implement them for your own project with the building blocks provided in client_golang.
The repository already has a lot of types, and I'd like to avoid putting even more there for rather special use cases.

**Comment by baryluk** [comment]
Ok. Lets leave this as closed. I will try implementing something nice, but you are right it might not be easy to do without templates ;) And compare to manually creating Collector (size of code, convenience, etc).

Good that you are aware of these design considerations. Thanks!
