### ISSUE TITLE
Is there a way to get current counter value?

### ISSUE THREAD

**Issue by icamys** [prometheus/client_golang#412]

**Comment by beorn7** [comment]
Yes:

```Go
func readCounter(m prometheus.Counter) float64 {
    pb := &dto.Metric{}
    m.Write(pb)
    return pb.GetCounter().GetValue()
}
```

If you wonder, why is is so complicated, have a look at #58 (where this example is taken from). Or look for provious discussions.

In general, it makes more sense to ask questions like this on the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users) rather than in a GitHub issue. On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.

**Comment by icamys** [comment]
@beorn7 Thanks for response and sorry for asking here. I was not aware of the mailing list existence.

**Comment by jeffwidman** [comment]
For more context on this, also see this comment: https://github.com/prometheus/client_golang/issues/486#issuecomment-433345239
