### ISSUE TITLE
Hmm, so long time don't have a stable release, should i just consider using the latest commit?

### ISSUE THREAD

**Issue by lnshi** [prometheus/client_golang#421]
As title.

**Comment by beorn7** [comment]
Yes. This is described here: https://github.com/prometheus/client_golang#important-note-about-releases-versioning-tagging-stability-and-your-favorite-go-dependency-management-tool

It makes more sense to ask questions like this on the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users) rather than in a GitHub issue. On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.
