### ISSUE TITLE
Internal Race Conditions make metric reporting unreliable

### ISSUE THREAD

**Issue by valarauca** [prometheus/client_golang#432]
I have reasons to believe this library is dropping data due to a potential internal race condition(s) in the registry's collection mechanism. I have had trouble reproducing this as it only seems to present randomly with my company's closed source application. 

To fully describe the bug, I have a `Counter` which is internally incremented after a web-api route is exercised. Before the counter is activated, we log a `INFO` statement. Currently I'm seeing the `INFO` log statements, but not the `Counter` changes.There are no branches just 2 lines of code similar too

```go
route.log.Info("work submitted")
route.metrics.Add(1)
```

When the application is restarted, the `Counter` will in-fact appear, sometimes this requires multiple. Likewise a single, or multiple restarts may result in the `Counter` disappearing. So it seems like pure chance if the `Counter` is being collected, or not. 

Having _all_ of our metrics collected is useful as we use them for alerting and monitoring of our application. 

---

We are using commit: `c5b7fccd204277076155f10851dad72b76a49317`, and `go version 1.10`, we're targeting `musl AMD64` linux environment namely alpine. 

 I gave a tentative review of recent patches (newer then our hash), but they didn't seem to affect the over collection mechanism.

**Comment by valarauca** [comment]
I've upgraded our internal dependencies to the latest version, and the problem persists.

**Comment by beorn7** [comment]
Thanks for the report.

However, to debug this, we really need a piece of code that reproduces the problem. It's OK if it only happens rarely, but not having any code that ever runs into the problem will make it impossible to even understand what the problem is.

This library is used a lot in production code, and something like this wasn't reported yet. My wild guess is that there might be a race in the way you are using the code.

Have you tried to run your code with the race detector enabled?
