### ISSUE TITLE
Can't use Variable Labels.

### ISSUE THREAD

**Issue by pault84** [prometheus/client_golang#461]
We currently use Prometheus to report the metrics of our product successfully.
I've recently had an ask from our customers to report these metrics with user-specified labels so they can filter the stats better. 

I'm having some serious issues getting this to work. I've seen 2 cases.
1. The larger label map gets created first and a subset will work.
2. metric without labels gets created first and then a user creates a new object with labels and I can't get these to be published.

Is there a workaround for this?
Delete won't work because it'll never match what I want to delete.
Is there a recommended workflow for this?

**Comment by beorn7** [comment]
I'm not quite sure I understand the problem. In any case, it seems like it's more a usage question than a bug report. It makes more sense to ask the former on the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users) rather than in a GitHub issue. On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.

I recommend to post your question on the mailing list, along with code examples to clarify what you are trying to do.

Thanks.
