### ISSUE TITLE
Don't compile example

### ISSUE THREAD

**Issue by gitchander** [prometheus/client_golang#468]
$ go build

# github.com/prometheus/client_model/go
../../../client_model/go/metrics.pb.go:96:31: undefined: proto.InternalMessageInfo
../../../client_model/go/metrics.pb.go:141:27: undefined: proto.InternalMessageInfo
../../../client_model/go/metrics.pb.go:179:29: undefined: proto.InternalMessageInfo
../../../client_model/go/metrics.pb.go:218:30: undefined: proto.InternalMessageInfo
../../../client_model/go/metrics.pb.go:265:29: undefined: proto.InternalMessageInfo
../../../client_model/go/metrics.pb.go:317:29: undefined: proto.InternalMessageInfo
...

**Comment by beorn7** [comment]
You have to update your dependencies, presumably `github.com/golang/protobuf/proto`.

A `go get -u` should do the trick.

If you have further questions, I recommend to ask on the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users) rather than in a GitHub issue. On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.
