### ISSUE TITLE
Race Condition between Register, Set and Serve

### ISSUE THREAD

**Issue by jnovack** [prometheus/client_golang#473]
I have a gauge, I *NEVER* want this gauge to be return zero (`0`) on the `/metrics` page (I can't be the only person).  I would rather it not be there (*a metric that can't be collected does not exist*)

The normal course of action would be to `.Register()` then `.Set()`.  However, if a request comes in between `.Register()`, and `.Set()`, the value of the Gauge is `0`.

The other option is to `.Set()`, then `.Register()`, but at that point, you are checking after every `.Set()` if you need to still need to register the Gauge (in some way, e.g. mutex, `AlreadyRegistered` err, or boolean) so it can show. 

I do not have the option of waiting to start the http engine until all Gauges are filled, as they may take a while.

How does someone solve this?

**Comment by jnovack** [comment]
For the person who finds this later.

Use labels!

Metrics with labels do not get initialized (or shown) until they exist.

**Comment by beorn7** [comment]
You can even create a GaugeVec with zero labels, if that help in that case.

https://godoc.org/github.com/prometheus/client_golang/prometheus#NewGaugeFunc might also help in some of those usecases.

In general, it makes more sense to ask questions like this on the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users) rather than in a GitHub issue. On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.
