### ISSUE TITLE
How to temporarily suspend GaugeVec?

### ISSUE THREAD

**Issue by kempeng** [prometheus/client_golang#475]
Hi,

Is it possible to temporarily stop publishing values using GaugeVec()? 

I'm using WithLabelValues().Set(val) to update values. If I stop setting values, prometheus will continue to pull the last value, how I can I make prometheus not to pull any value, until I want to resume it again?

Thanks.

**Comment by beorn7** [comment]
You can use [`Unregister`](https://godoc.org/github.com/prometheus/client_golang/prometheus#Unregister) to remove the `GaugeVec` from the registry. (You have to re-register resume exposition.) Or you can remove individual metrics from the `GaugeVec` with [`Delete`](https://godoc.org/github.com/prometheus/client_golang/prometheus#GaugeVec.Delete).

***However***, what you are asking for above really really smells like something you should not do as a good Promethean. Ideally, a metric should not come and go over the lifetime of a binary.

In different news, it makes more sense to ask questions like this on the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users) rather than in a GitHub issue. On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.

Thus, I'll close this issue. If you have more questions, please use the mailing list.
