### ISSUE TITLE
refactor and simplify the http client tests 

### ISSUE THREAD

**Issue by krasi-georgiev** [prometheus/client_golang#485]
after reviewing a PR that included changes in the client tests I think these could be simplified to make it easier to follow and understand.

possibly using https://golang.org/pkg/net/http/httptest

**Comment by si74** [comment]
I'd be happy to work on this!

**Comment by krasi-georgiev** [comment]
Appreciated!

**Comment by krasi-georgiev** [comment]
Just finished reviewing https://github.com/prometheus/client_golang/pull/508 and I realise that for the test it uses a mock server so any changes in the Prometheus api won't be caught in this client tests. So it would be even better if we can tests against the  actual Prometheus server(or at least the web api package) as this will ensure the most stable behaviour.

**Comment by geekodour** [comment]
@krasi-georgiev how would you recommend running an actual Prometheus server for this? we can start and stop a docker instance running Prometheus and then running the tests against it. but this will require writing something to set and stop Prometheus. will it be fine to work on this under this issue, or should we open another issue for that?

if @si74 is not working on this one, I can take this up.

**Comment by krasi-georgiev** [comment]
My first suggestion is to try and import and use the Prometheus web module directly.
https://github.com/prometheus/prometheus/tree/master/web

**Comment by geekodour** [comment]
@krasi-georgiev okay got it, will try to start this today.

**Comment by geekodour** [comment]
@krasi-georgiev I was working on this, I've added http handlers and mux. The http handler will able to respond differently to requests based on the parameters/url etc.

but following are two testcases from current tests for `doQuery` in which `reqParam` is same on both of the cases and because the `Do` function is completely controlled by the test file, it is returning an error on the same. Is this intended behavior for the testcase?

https://github.com/prometheus/client_golang/blob/d2ead25884778582e740573999f7b07f47e171b4/api/prometheus/v1/api_test.go#L168-L200

Secondly, 
I am just trying to get httptest into the test file initially and should the api/v1 module be used instead?
https://github.com/prometheus/prometheus/tree/master/web/api/v1

But I am not sure how can we go about making the actual api/v1 module useful here as we'll have to mock the response anyway. isn't it?

**Comment by krasi-georgiev** [comment]
> but following are two testcases from current tests for doQuery in which reqParam is same on both of the cases and because the Do function is completely controlled by the test file, it is returning an error on the same. Is this intended behavior for the testcase?

I am not sure, but maybe if you look deeply there is some difference.

> I am just trying to get httptest into the test file initially and should the api/v1 module be used instead?
prometheus/prometheus:web/api/v1@master

yes only v1 should be included.

> But I am not sure how can we go about making the actual api/v1 module useful here as we'll have to mock the response anyway. isn't it?

no I was hoping that we can add some actual data and use the `api/v1` to return actual results. I haven't looked through the code yet, but in theory it should be possible.

**Comment by geekodour** [comment]
okay, It's working fine with httptest now, will try sending the PR today.

**Comment by beorn7** [comment]
Looking at the discussion in #528, this doesn't really look like low-hanging fruit anymore.

@geekodour are you still planning to do the follow-up PR you mentioned in #528?

**Comment by geekodour** [comment]
@beorn7 I totally forgot about this PR. thanks for reminding. I can continue looking into this, but my only concern is how do we plan to simulate the api responses for targets?
for eg.

https://github.com/prometheus/client_golang/blob/20428fa0bffcb4ee7a7941545ae0df9acdc9d8a7/api/prometheus/v1/api_test.go#L737-L754

so for this, prometheus will need a target to respond to the api request. how do we simulate that?

**Comment by beorn7** [comment]
@krasi-georgiev do you have an answer for that?

**Comment by krasi-georgiev** [comment]
I can't remember exactly, but I think we discussed the idea to spin up a CI job that just runs a prometheus container and send the request to an actual Prometheus API

**Comment by geekodour** [comment]
> spin up a CI job that just runs a prometheus container and send the request to an actual Prometheus API

can't we use the prombench infrasture for this? by adding manifest files to setup the targets and rules that the test expects. splitting this into three steps in travis config:
- one to setup the test components
- one to run the actual test against the prometheus api server
- one to destroy the setup

Otherwise maybe will have to create a custom docker image to have it load rules and targets if we want to run it inside a single CI job. The first approach gives us more flexibility i think.

@juliusv @krasi-georgiev what do you think?

**Comment by krasi-georgiev** [comment]
I would say let's try with just circle

You can put the config in env variable and have those converted into config files

See this tool that i developed recently
https://github.com/arribada/EnvToFile

**Comment by geekodour** [comment]
okay sure, thanks for the pointers. I'll work on this.

**Comment by beorn7** [comment]
@geekodour what's the state of this issue?

We have CircleCI now running for this repo, too, thanks to @simonpasquier .

**Comment by beorn7** [comment]
I have embarrassingly little context on the API client. :o(

But from my little knowledge, I'd say nothing fundamentally has changed. Go for it!

**Comment by krasi-georgiev** [comment]
not a priority so closing
