### ISSUE TITLE
why InstrumentHandler* only support "code" or "method" label?

### ISSUE THREAD

**Issue by samt42** [prometheus/client_golang#520]
why not support "request_uri" "host" etc.

**Comment by beorn7** [comment]
The InstrumentHandler middlewares are meant to cover the most common cases. Usually, you would not like to track the request URI or the host in a label as that s prone to cardinality explosion. However, if you really want to, you can still do it by using the more basic instrumentation primitives.
This is similar to https://github.com/prometheus/client_golang/issues/491 .See there for more explanations.

Also, it makes more sense to ask questions like this on the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users) rather than in a GitHub issue. On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.
