### ISSUE TITLE
How do I manipulate the results of the Histogram in my code?

### ISSUE THREAD

**Issue by Lynzabo** [prometheus/client_golang#522]
How do I generate normal distribution data for the histogram index data in the Go language code, such as getting the minimum, maximum, p99, etc. Like the histogram_quantile function, does prometheus have an API interface?

**Comment by beorn7** [comment]
I'm not sure I really understand your question. This all sounds like questions about PromQL and about the Prometheus server, not really a client library question.

In any case, it makes more sense to ask questions like this on the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users) rather than in a GitHub issue. On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.
