### ISSUE TITLE
Expose main module version as info metric in Go 1.12

### ISSUE THREAD

**Issue by brian-brazil** [prometheus/client_golang#539]
Go 1.12 will adds https://tip.golang.org/pkg/runtime/debug/#ReadBuildInfo to get build module information. This seems like it would be useful to expose by default as an info metric, if modules are enabled.

We'd need to be careful this was only enabled on 1.12 via build tags.

**Comment by beorn7** [comment]
Go 1.12 is in general use now, and so are modules.

I like the idea, but we need to flesh out the details. Options I can see:

1. Expose only `Version`, consider it harmless and make it part of the Go collector.
2. Like (1) but create an option to disable it (in which case we have to decide if we want it in a separate collector as we would otherwise need to give `NewGoCollector` an options argument after all.
3. Also add the main package `Path` and/or the main module `Path`. This has to be optional in any case.

Thoughts anybody?

**Comment by beorn7** [comment]
Here is something to look at for inspiration: https://povilasv.me/exposing-go-modules-to-prometheus/

**Comment by beorn7** [comment]
https://github.com/povilasv/prommod includes all the dependencies, but (interestingly) not the BuildInfo of the main module itself. (Or I am missing something. @povilasv , perhaps you can confirm.)

I guess we can do something similar to prommod, but with the main module included.
Or we can only do the main module for a start.

In any case, I am more and more convinced not to do this by default. For one, because it risks accidental disclosure of internal package structures. And then the number of dependencies could be quite significant, creating many metrics.

So perhaps it should just be a separate collector that people can add if they want, with an option if only the main module should be included or also the dependencies.

**Comment by povilasv** [comment]
@beorn7 I can contribute `prommod` to you guys if you want it :) This could live in https://github.com/prometheus-community and be an optional package that people can import if they need it. 

Re main module I did it in order not to duplicate information. If you use https://github.com/prometheus/common/blob/master/version/info.go then you essentially get the same information.

**Comment by beorn7** [comment]
Personally, I don't think it makes a huge difference if `prommod` lives in your own org or in prometheus-community. Just put it where you think it makes most sense.

WRT to prometheus/client_golang, I'm thinking more about a lightweight thing that people can just activate if they like, without pulling in another dependency and without further ado. https://github.com/prometheus/common/blob/master/version/info.go for example, requires the user to also set some build variables. And of course, like `prommod`, it also provides more functionality than just metrics.

I guess I'll code something that just does metrics, and includes the main module. The doc comment will then mention `prommod` and the buildinfo in `common` for users that want something more involved.

**Comment by povilasv** [comment]
Cool, I think I would like for prommod to be in prometheus-community. Do you know who should I contact to get repo created? 

Re main module I just remembered that I would always get incomplete data.

For example:

```
package main

import (
	"fmt"
	"log"
	"net/http"
	"runtime/debug"

	"github.com/prometheus/client_golang/prometheus"
	"github.com/prometheus/client_golang/prometheus/promhttp"
	"github.com/prometheus/common/version"
)

func main() {
	prometheus.MustRegister(version.NewCollector("app_name"))
	http.Handle("/metrics", promhttp.Handler())

	buildInfo, ok := debug.ReadBuildInfo()
	if !ok {
		log.Fatal("err !ok")
	}

	fmt.Printf("Output: %#v\n", buildInfo.Main)

	log.Fatal(http.ListenAndServe(":8080", nil))
}
```

```
export GO111MODULE=on

go mod init
go build
```
Output:

```
./prom-build-test
Output: debug.Module{Path:"hello/prom-build-test", Version:"(devel)", Sum:"", Replace:(*debug.Module)(nil)}
```

**Comment by beorn7** [comment]
Yeah, I saw the same thing. I'll do some more research about the required circumstances to see a proper version in the main module.

WRT prometheus-community: I believe it's still in flux how it will actually work and be governed. I guenn @RichiH might be the best to contact at this point.

**Comment by povilasv** [comment]
Thanks. Will contact @RichiH

**Comment by beorn7** [comment]
To get `BuildInfo` filled in a reasonable way, you have to `go get` the code from the actual repo and with modules activated.

Run `GO111MODULE=on go run github.com/beorn7/modtest` to demonstrate.

Based on that, I'll create a simple, optional collector for client_golang and will point to @povilasv 's project for more involved needs.

**Comment by beorn7** [comment]
Simple solution is in place now. It could even be combined with `prommod` (resulting in `go_build_info` for the main module and `go_mod_info` for the dependencies).

**Comment by povilasv** [comment]
Awesome :) 

FYI regarding the `prommod` move to prometheus community organization, I've tried to contact @RichiH, but didn't get any response. So I've pinged @brancz he said he will discuss the possibility with others :)
