### ISSUE TITLE
Decouple metrics in NewProcessCollector

### ISSUE THREAD

**Issue by logicalhan** [prometheus/client_golang#578]
This is a feature request. 

In Kubernetes, we use (in some cases) custom registries and are planning to migrate off of the deprecated global prom registry. When we use custom registries, we would like to be able to add some (but not all) the metrics from NewProcessCollector (specifically we want to be able to add 'process_start_time_seconds'). Unfortunately the coupling in NewProcessCollector means we cannot do so without bringing in all of the other process metrics. It would be nice if there was some decoupling that would enable us to do so.

**Comment by beorn7** [comment]
I've always been afraid people will ask for this eventually… :o)

So yeah, I think it's a fair thing to ask. But what would be a good interface for this? A filter regexp? A boolean option for each metric in the collector?

What's the motivation for only adding some of the metrics? Just so that I understand what course of action would and would not help your cause.

**Comment by logicalhan** [comment]
There is some desire to keep kubelet metrics as light as possible. Specifically, we have one metrics endpoint in the kubelet currently exposes a very small set of metrics ([liveness and readiness probe results](https://github.com/kubernetes/kubernetes/blob/d881c0d77bef9c268433c6ec0770fcc80ab79c59/pkg/kubelet/server/server.go#L322-L327)), which are all counters. We would like to preserve the process_start_time_seconds for counter data fidelity. We don't really have a usecase for the other 6 metrics which are dragged in with the `processCollector`.

**Comment by brian-brazil** [comment]
> We would like to preserve the process_start_time_seconds for counter data fidelity. 

I'd suggest not making this change in that case. Once this client supports OpenMetrics, you'll get the creation timestamp for each counter out of the box.

**Comment by logicalhan** [comment]
> Once this client supports OpenMetrics, you'll get the creation timestamp for each counter out of the box.

When is that slated? Is there a spec for that?

**Comment by beorn7** [comment]
OpenMetrics is not yet finalized. For me, as a relative outsider, it's not even in a state where I can meaningfully design the client library around it.
Not going into details, it's certain that we are not talking about "next month" or something.

If `process_start_time_seconds` is the only metric you need, and for different reasons than the actual process metric, would it perhaps make sense to create that metric explicitly? It should be quite easy to set up in an `init` function.

**Comment by logicalhan** [comment]
Yes, actually the plan was to create a version of the metric internally and file a ticket here and hope that one day we could swap out our internal version for an officially supported variant. Any chance that may happen?

**Comment by beorn7** [comment]
Let's say if there is more than this one use case, I'll consider it.
For a single use case, a handful of lines for a custom implementation doesn't sound like a huge burden.

I'm afraid that we'll git all kind of single-use-case demands to have exactly this or that metric but not the others in any of the collectors (process collector or Go collector).

**Comment by logicalhan** [comment]
For sure, in the use case we are envisioning, it is trivial to implement our own version of it. However, it feels like one of those things that the prom client should provide, given the sort of fundamental requirement of having a process start timestamp for counter data fidelity. 

But yeah, I get it, there are feature requests and then there are feature requests. The impact to our project is minimal, it just seemed like, philosophically, the sort of thing the prom client should provide.

**Comment by beorn7** [comment]
The Prometheus client _does_ provide the feature, just that it comes with all the other process metrics. Separating it out would only help those users that need `process_start_time_seconds` _and at the same time_ have the need to get rid of the other process metrics (_and_ cannot wait for OpenMetrics support).

If that intersection has more than one user, we can still think about supporting it directly. I'll leave this issue open for a while to see if somebody else chimes in.

**Comment by logicalhan** [comment]
Sounds reasonable to me. Thanks for hearing me out :)

**Comment by beorn7** [comment]
Nobody chimed in so far, so I'll close it. (I'm still subscribed to this issue. If anybody has a strong need to follow up, feel free to do so.)

**Comment by fpetkovski** [comment]
We encountered a similar problem in kube-state-metrics. KSM currently exports kube-api metrics and telemetry metrics on different ports. There is a request to enable merging all metrics in one endpoint, but that would break our filters since we can't control metrics exported by the process collector.

**Comment by beorn7** [comment]
Could you be more specific what "break our filters" means?

**Comment by beorn7** [comment]
I see. I guess that's a more general problem then than just making the ProcessCollector configurable. 

Perhaps you could wrap all the externally provided collectors with a `FilteringCollector` and then filter out the metrics in the `Collect` method… It would be quite expensive as you have to render each metric with `Metric.Write`, but if it only affects a few metrics, that might be acceptable as an interim solution. (A more efficient implementation of filtering by name would be possible directly in client_golang/prometheus, because it could access the unexported fields of `Desc`.)

This would go into the direction of https://github.com/prometheus/client_golang/issues/135 , something being discussed for a long time…

I guess you could follow up there. Or file a more specific feature request as a separate issue.

**Comment by fpetkovski** [comment]
Thanks for the suggestion, that could indeed work. The only issue is that `Metric.Write` does not serialize the metric name: https://github.com/prometheus/client_golang/blob/main/prometheus/value.go#L124. 

It seems that the name is contained in `Desc.fqName`, but it's not added to the label pairs when the metric is written out to a DTO. Is this expected, or is it just an oversight?

**Comment by beorn7** [comment]
Yes, that's expected. The metric name is only part of the MetricFamily (in the old protobuf-based data model). So yeah, without access to `Desc.fqName`, you cannot filter by name in the Collector. (You could do something on the Gatherer level, where you act on the MetricFamily level.)

**Comment by fpetkovski** [comment]
Perfect, wrapping the Gatherer seems to work. It's also simpler to work with it since there's no need to deal with channels. Thanks for the pointers :+1:
