### ISSUE TITLE
Support for DELETE calls to PushGateway

### ISSUE THREAD

**Issue by nnoto** [prometheus/client_golang#611]
Is there any plan to support the DELETE API for the PushGateway?
With the package as-is, we are able to push metrics to the PushGateway, but not able to clean them up if they are not intended to be overwritten.

**Comment by beorn7** [comment]
Since the delete call has no payload, there is really not much that the client library would add. It really boils down to:

```Go
	req, err := http.NewRequest(http.MethodDelete, "http://localhost:9091/metrics/job/some_job", nil)
	if err != nil {
		panic(err)
	}
	rsp, err := http.DefaultClient.Do(req)
	if err != nil {
		panic(err)
	}
	fmt.Printf("Delete request resulted in %q.\n", rsp.Status)
```

I'm reluctant to add a feature to the library that essentially saves two or three lines of code and also does something very common (sending out a DELETE request with the standard http package) in a less obvious way (by looking at the function name, you cannot know what it is doing under the hood).

On the other hand, it would be quite easy and kind of elegant to add a `Delete` method to the Pusher.
I'll give it a try…

**Comment by nnoto** [comment]
Thanks for the reply, I can understand why the library doesn't support the delete call.

If you were to add a Delete method to the Pusher, what would be the resulting behavior when called?
If a Pusher is deleted, would the metrics pushed by the Pusher to the PushGateway still exist in the PushGateway?

**Comment by beorn7** [comment]
The suggested `Delete` method would not delete the Pusher “object” itself. It would cause the Pusher to send a DELETE request with the configured grouping key.

You can trigger a very similar effect already now by simply pushing with an empty Pusher (it will leave a `push_time_seconds` metric around, though):
```Go
push.New("http://example.org/metrics", "my_job").Push()
```

Or with a more complex grouping key:
```Go
push.New("http://example.org/metrics", "my_job").Grouping("foo", "bar").Push()
```
