### ISSUE TITLE
Update go_gc_duration_seconds HELP text

### ISSUE THREAD

**Issue by thinkeridea** [prometheus/client_golang#618]
```
# HELP go_gc_duration_seconds A summary of the GC invocation durations.
# TYPE go_gc_duration_seconds summary
go_gc_duration_seconds{quantile="0"} 1.1717e-05
go_gc_duration_seconds{quantile="0.25"} 1.5126e-05
go_gc_duration_seconds{quantile="0.5"} 1.9535e-05
go_gc_duration_seconds{quantile="0.75"} 4.3568e-05
go_gc_duration_seconds{quantile="1"} 0.000384508
go_gc_duration_seconds_sum 669.380082897
go_gc_duration_seconds_count 8.186899e+06
```
How these data should be used to facilitate analysis of GC performance.

I use the following queries in grafana to get graphs. I can't get effective information or hints from them. I can't understand the average and maximum time-consuming of gc, and the proportion of the maximum time-consuming.

```
avg(irate(go_gc_duration_seconds_sum{instance=~"$instance",project=~"$project"}[$interval]))
avg(go_gc_duration_seconds{project=~"$project", instance=~"$instance"}) by (quantile)
```

If possible, please explain how bitmap data can be queried to obtain graphs and how to analyze to obtain valid data, and use the above data as an example.

**Comment by beorn7** [comment]
Those metrics are coming directly from the Go runtime. For a better understanding of them, I recommend asking in relevant Go forums.

For Prometheus related questions, it makes more sense to ask them  on the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users) rather than in a GitHub issue. On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.

**Comment by bboreham** [comment]
I had the same question; this page is the top hit on Google for `go_gc_duration_seconds_sum` and I could not find any other page which answered the question.  I had to read the code.

So, for the benefit of future visitors: the key insight is that this metric is the _pause_ time, and since Go version 1.6 [pause times have been miniscule](https://blog.golang.org/ismmkeynote) - a few hundred microseconds max, which won't impact you unless you have seriously low latency requirements.  For ordinary folks there is nothing much to be learned from this metric.

The Prometheus metric has a misleading name now; the _duration_ of GC can be several seconds, but  almost all of it runs in the background so doesn't directly impact execution.

**Comment by beorn7** [comment]
We could update the HELP text for the metric.

Reopening and renaming this.

**Comment by jasonliu747** [comment]
010-64429988

**Comment by jasonliu747** [comment]
010-64429988
