### ISSUE TITLE
how to unregister a SummaryVec

### ISSUE THREAD

**Issue by hedemonde** [prometheus/client_golang#669]
I try use Unregister(), But it doesn't work.
   when I registe the same name SummaryVec again.
   I get a error :
  a previously registered descriptor with the same fully-qualified name as Desc{fqName: "test_6791_summary", help: "", constLabels: {}, variableLabels: [appId appVersion os osVersion packageName t1 t3 t4 t6 t7]} has different label names or a different help string
 
 how can I unregister a SummaryVec

**Comment by beorn7** [comment]
`Unregister` will remove the `Collector` from the registry, but any new `Collector` registered with the same registry still has to be consistent with the unregistered `Collector`, i.e. you cannot define new help strings or new label dimensions in that way. This is [documented in the doc comment for the `Unregister` method](https://godoc.org/github.com/prometheus/client_golang/prometheus#Registerer).

The intention of the library is that a binary will only ever expose consistent metrics over its lifetime. If you really wanted to break that behavior, you would need to create a whole new registry.

If you have more questions, please do so on the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users) rather than in a GitHub issue. On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.
