### ISSUE TITLE
panic error, summary ot the situation

### ISSUE THREAD

**Issue by fcddk** [prometheus/client_golang#674]
1: inconsistent label cardinality: expected 9 label values but got 8 in []string
2: Register error: duplicate metrics collector registration attempted

Are there other notable situations?

And how to avoid the occurrence of "inconsistent label cardinality: expected 9 label values but got 8 in []string", how strong the program should be (not manually written)
Any good suggestions?

**Comment by beorn7** [comment]
It makes more sense to ask questions like this on the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users) rather than in a GitHub issue. On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.
