### ISSUE TITLE
prometheus.DefaultGatherer add custom labels

### ISSUE THREAD

**Issue by fcddk** [prometheus/client_golang#678]
I want to add lables(dimensions) to the metric(prometheus.DefaultGatherer), and don't find a good way to achieve it, is there any good advice?

**Comment by beorn7** [comment]
It makes more sense to ask questions like this on the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users) rather than in a GitHub issue. On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.
