### ISSUE TITLE
the function prometheus.WrapRegistererWith is insufficient

### ISSUE THREAD

**Issue by fcddk** [prometheus/client_golang#679]
I think prometheus.WrapRegistererWith can't add label for a Registry is a failed design. 
I dream of such a scene:
	reg := prometheus.NewRegistry()
	labels := prometheus.Labels{"service": "xxxx"}
	prometheus.WrapRegisterWith(labels, reg)
	reg.Register(prometheus.NewGoCollector())
	reg.Register(prometheus.NewBuildInfoCollector())

**Comment by beorn7** [comment]
I think `WrapRegistererWith` does what you want. You are probably just using it in the wrong way. There is an [example](https://godoc.org/github.com/prometheus/client_golang/prometheus#example-Collector) in the docs (in the function `NewClusterManager`).

Suggested modification of your code:
```Go
reg := prometheus.NewRegistry()
labels := prometheus.Labels{"service": "xxxx"}
wrappedReg := prometheus.WrapRegisterWith(labels, reg)
wrappedReg.Register(prometheus.NewGoCollector())
wrappedReg.Register(prometheus.NewBuildInfoCollector())
```

However, note that you should not use `WrapRegistererWith` to add the same label to _all_ your exposed metric. That's much better done with target labels. They are added by the Prometheus server.

If you have more questions, please use the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users) rather than in a GitHub issue. On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.
