### ISSUE TITLE
Registry Counter panic: duplicate metrics collector registration attempted

### ISSUE THREAD

**Issue by bigpigeon** [prometheus/client_golang#716]
### client version

 github.com/prometheus/client_golang v1.4.1

### go.mod 

```
module github.com/bigpigeon/Test/go/prometheus_example_http
go 1.13

require (
	github.com/prometheus/client_golang v1.4.1
	github.com/prometheus/common v0.9.1
)

```

### Problem

when I Registry `prometheus.Counter` with `prometheus` must be panic with `duplicate metrics collector registration attempted`

source code

```

package main

import (
	"github.com/prometheus/common/expfmt"
	"net/http"
	"time"

	"github.com/prometheus/client_golang/prometheus"
	"github.com/prometheus/client_golang/prometheus/promauto"
)

func recordMetrics(opsProcessed prometheus.Counter) {
	go func() {
		for {
			opsProcessed.Inc()
			time.Sleep(2 * time.Second)
		}
	}()
}

func main() {

	opsProcessed := promauto.NewCounter(prometheus.CounterOpts{
		Namespace: "bigpigeon",
		Subsystem: "test",
		Name:      "xxx",
		Help:      "The total number of processed events",
	})

	prometheus.MustRegister(opsProcessed)

	recordMetrics(opsProcessed)

	mfs, err := prometheus.DefaultGatherer.Gather()
	if err != nil {
		panic(err)
	}
	http.HandleFunc("/metrics", func(writer http.ResponseWriter, request *http.Request) {
		for _, mf := range mfs {
			if mf.Help != nil && *mf.Help == "test histogram bucket" {
				if _, err := expfmt.MetricFamilyToText(writer, mf); err != nil {
					if err != nil {
						panic(err)
					}
				}
			}
		}
	})
	http.ListenAndServe(":9090", nil)
}
```

**Comment by bwplotka** [comment]
Hi :wave: 

This is expected, as you used [promauto](https://godoc.org/github.com/prometheus/client_golang/prometheus/promauto) which automatically registers the metric. (: 

You have few options (you can choose any of those three):

1. Use `prometheus` package for creating metrics: `prometheus.NewCounter(prometheus.CounterOpts{`
2. Don't register `prometheus.MustRegister(opsProcessed)`. `promauto` already does that.
3. **Better** Use custom registry to have explicit control on what is registered and when:

```
reg := prometheus.NewRegistry()
opsProcessed := promauto.With(reg).NewCounter(prometheus.CounterOpts{
		Namespace: "bigpigeon",
		Subsystem: "test",
		Name:      "xxx",
		Help:      "The total number of processed events",
	})
// No need to register with prometheus.MustRegister(opsProcessed) anymore.
```

Let us know if you have more questions! :hugs:  Otherwise closing (:

**Comment by beorn7** [comment]
It makes more sense to ask questions like this on the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users) rather than in a GitHub issue. On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.

**Comment by 1a1a11a** [comment]
@beorn7 GitHub is easier to find for someone not on the mailing list and benefits more people

**Comment by jeeftor** [comment]
@1a1a11a - Fully agree with this

**Comment by meetsubhojit** [comment]
> @beorn7 GitHub is easier to find for someone not on the mailing list and benefits more people

and its google searchable
