### ISSUE TITLE
SummaryVec not recording individual durations, only count and sum

### ISSUE THREAD

**Issue by pbnsilva** [prometheus/client_golang#722]
version: `v1.1.0`
revision: `170205fb58decfd011f1550d4cfb737230d7ae4f`

How I'm creating the SummaryVec:
```
durationSummary := prometheus.NewSummaryVec(prometheus.SummaryOpts{
                Namespace: namespace,
                Name:      "api_request_duration_ms",
                Help:      "Time in milliseconds spent in API code while processing the request",
        }, []string{"handler", "status_code"})

responseTimeMilliseconds := mustRegisterOrGet(durationSummary).(*prometheus.SummaryVec)
```

And observing:
```
responseTimeMilliseconds.With(
      prometheus.Labels{
                                "handler":     handlerName,
                                "status_code": status,
                        }).Observe(duration)
```

Yet, no `api_request_duration_ms` is recorded, only `api_request_duration_ms_count` and `api_request_duration_ms_sum`, which I can't use to look at quantiles:
```
api_request_duration_ms_sum{handler="test",status_code="200"} 14604
api_request_duration_ms_count{handler="test",status_code="200"} 1
```

What am I missing?

Thank you

**Comment by beorn7** [comment]
You have to specify objectives. The default is to have no objectives, see the `Objectives` field in [`SummaryOpts`](https://pkg.go.dev/github.com/prometheus/client_golang/prometheus@v1.5.0?tab=doc#SummaryOpts) and the [example for Summaries](https://pkg.go.dev/github.com/prometheus/client_golang/prometheus@v1.5.0?tab=doc#example-Summary).

It makes more sense to ask questions like this on the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users) rather than in a GitHub issue. On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.
