### ISSUE TITLE
How to convert client_golang Query result to json format?

### ISSUE THREAD

**Issue by L-maple** [prometheus/client_golang#735]
Hello!

### Problem:
I really have trouble dealing with the client function Query's result, which is like the following:
`{namespace="monitoring", pod="grafana-78c97f858d-mwndr"} => 0.051599181750078355 @[1586853469.877]`
So how can I convert this to json or other format?

### How to get a similar result:
I just try the example provided by this registry， the code address is https://github.com/prometheus/client_golang/blob/master/api/prometheus/v1/example_test.go。
func ExampleAPI_query() will print the result.
	
### So, My confusion is:
1. Is there any solution to this problem? 
2. How can I do this simply, apart from regex?

**Comment by beorn7** [comment]
In my understanding, it's the whole point of the API client library to convert the JSON format provided by the [Prometheus query API](https://prometheus.io/docs/prometheus/latest/querying/api/) into a [data model inside of your Go program](https://github.com/prometheus/common/model). Converting back into JSON would defeat the purpose. If you want the JSON, you should probably use your usual JSON tooling to query the Prometheus API directly.

I might also miss your point, but in that case, I recommend to ask more questions on the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users) rather than in a GitHub issue. On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.
