### ISSUE TITLE
NewGoCollector with options

### ISSUE THREAD

**Issue by helloyi** [prometheus/client_golang#782]
Expect to specify the namespace of prometheus.NewGoCollector.

thanks!

**Comment by beorn7** [comment]
Actually, you shouldn't change the names of the metrics collected by the Go collector. The whole idea is that they are the same across all binaries built with Go.

If you have an esoteric use case where you really need to prefix the names (and you should really really know what you are doing!), then you can use https://pkg.go.dev/github.com/prometheus/client_golang@v1.7.1/prometheus?tab=doc#WrapRegistererWithPrefix .

If you have more questions, please use the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users) rather than in a GitHub issue. On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.

**Comment by helloyi** [comment]
I understand.
prometheus.WrapRegistererWithPrefix is exactly what I want, thanks!
