### ISSUE TITLE
Example of microservice promQL query to Prometheus

### ISSUE THREAD

**Issue by lukekhamilton** [prometheus/client_golang#787]
Hey all, 

Has anyone got an example of how I have call Prometheus with a promQL query and get the results back into my golang based microservice? This would be super helpful. Or any tips where to look in this codebase or elsewhere?

Thanks

**Comment by beorn7** [comment]
It makes more sense to ask questions like this on the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users) rather than in a GitHub issue. On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.
