### ISSUE TITLE
Allow  namespace,subsystem and  labels values to be set in different usage context  for standard exports

### ISSUE THREAD

**Issue by bklaubos** [prometheus/client_golang#790]
Currently, standard exports, like `process_goroutines` are in "flat" namespace. 
(See https://github.com/prometheus/client_golang/pull/36/files for example)
There are usage context where a metric like `process_goroutines` needs to be given a context of namespace, subsystem and even constant labels.
Example:  we might run microservices in AWS and AZURE and so would like to namespace or label `process_goroutines` metrics as originated from a named microservice "X" and a cloud provider "AWS"
Currently, all standard exports like `process_goroutines` is flat with respect to  usage context

**Comment by beorn7** [comment]
In general, we recommend strongly to never change the names of standard metrics. It's their whole point to be named the same everywhere. Things like the cloud provider or the microservice names should all be configured as target labels.

If you still need to prefix those names (not recommended, really not!), you can use https://pkg.go.dev/github.com/prometheus/client_golang@v1.7.1/prometheus?tab=doc#WrapRegistererWithPrefix .

In general, it makes more sense to ask questions like this on the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users) rather than in a GitHub issue. On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.
