### ISSUE TITLE
Is there any way to  flush/rotate metrics stored in-memory on a periodic interval?

### ISSUE THREAD

**Issue by ganpatagarwal** [prometheus/client_golang#791]
We are using this package to instrument metrics from our application. Metrics generated by the app endpoints are consumed by Prometheus server.

We have seen that count of "scrape_samples_scrapped" keeps on accumulating over time, which starts consuming more chunk  of memory from Prometheus server.

Is there any way we can flush/rotate the collected metrics on application so as to reduce count of  samples to be scraped by Prometheus server?

**Comment by beorn7** [comment]
In general, you should know all metrics you expose in advance, so metrics should ideally never show up anew and never disappear from the exposition of a single binary. In practice, that's not always feasible. Metrics suddenly showing up are therefore normal, but I'd still avoid deliberately removing them. If you really need to, there are methods on metric vectors like https://pkg.go.dev/github.com/prometheus/client_golang@v1.7.1/prometheus?tab=doc#CounterVec.Delete . However, if you need to do that, perhaps you are not using metrics in the right way. Ever increasing cardinality is often a symptom for trying to shoehorn event logging into metrics collection.

However, for all of this, you should better refer to the usual community channels, see https://prometheus.io/community/ . In particular, it makes more sense to ask questions like this on the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users) rather than in a GitHub issue. On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.
