### ISSUE TITLE
Allowed HTTP methods shall be limited on metrics 

### ISSUE THREAD

**Issue by 4ndris** [prometheus/client_golang#794]
### Host operating system: output of `uname -a`

```Linux ca543372ca59 4.19.76-linuxkit prometheus/node_exporter#1 SMP Tue May 26 11:42:35 UTC 2020 x86_64 GNU/Linux```

### node_exporter version: output of `node_exporter --version`

```node_exporter, version 1.0.1 (branch: HEAD, revision: 3715be6ae899f2a9b9dbfd9c39f3e09a7bd4559f)```

### node_exporter command line flags
```/bin/node_exporter --path.rootfs=/host```

### Are you running node_exporter in Docker?
yes

It seems that node_exporter exposes metrics endpoints without limiting allowed HTTP methods, this way allowing to be invoked with GET, POST, PUT, DELETE. It is recommended to limit all the allowed methods to GET, HEAD (and POST in case its necessary) otherwise it shall return 405.

**Comment by roidelapluie** [comment]
Yes, I have moved the issue. Thanks @4ndris.

**Comment by beorn7** [comment]
Currently, the `http.Handler` implementations provided by `promhttp` are indeed completely ignorant of methods (you could even use made-up method names). The handler always behaves exactly the same. While I wouldn't claim that was a deliberate decision, what's exactly the impact or problem with that?

> It is recommended to limit all the allowed methods to GET, HEAD (and POST in case its necessary) otherwise it shall return 405.

While I could see people arguing that way, what is the source of this recommendation? A quick web search only reveals overeager "security" scanners complaining about certain methods being allowed. But I'm totally willing to learn about a recommendation of some weight and/or following a convincing line of argument.

In principle, I think it would not do any harm to only serve metrics on GET, but at this point, it will be hardly possible to restrict the method in the handler without a major version bump. I can see legitimate cases for using other methods than GET and HEAD (if users have wrapped the stock metrics handler with something else and read parameters from a POST form, for example), but more commonly I'd expect accidental usage of other methods that would suddenly stop to work. Since the current `promhttp` documentation nowhere requires the GET method, one might argue the currently (implicitly) documented behavior is to allow all methods, even if only GET makes sense semantically. 

A different question is if the method restriction should really be implemented the handler. Many popular HTTP router packages allow to register a handler for specifically one method, so it's easy to restrict the method if you want to. On the other hand, if a user has a weird use case where they really need a method different from GET, they needed to jump through many hoops to make that possible with a handler that is less permissive than the current one.

Another argument against doing the method restriction in the handler follows from RFC7231 itself:

    When a request method is received
    that is unrecognized or not implemented by an origin server, the
    origin server SHOULD respond with the 501 (Not Implemented) status
    code.  When a request method is received that is known by an origin
    server but not allowed for the target resource, the origin server
    SHOULD respond with the 405 (Method Not Allowed) status code.

From this, I'd argue 501 should be reported if the server has no endpoint (AKA target resource) whatsoever that understands the method. 405 should only be returned if the same server understands the method on some other endpoint. However, that decision cannot be made in the metrics handler.

If there are really good reasons and/or well established best practices to only allow GET and HEAD on the metrics endpoint, then we should add a recommendation to the documentation. But even then, we cannot change the behavior in v1, and because of the two arguments described above (fringe use cases that might still need a different method, and the 501 vs. 405 problem), I even have doubts if we should change it in v2.

**Comment by beorn7** [comment]
Closing this for lack of follow-up. I'm assuming for now that my reasoning above is correct.

Please follow up on this issue if you have to present contrary evidence.

In particular, if serving metrics on non-GET methods is really a problem, I'd like to know because then I can at least warn about it in the doc comment.
