### ISSUE TITLE
prevent metric scraping before synching state

### ISSUE THREAD

**Issue by benitogf** [prometheus/client_golang#810]
if a metric depends on a persisted state its possible that it shows the zero value while its synced, and this could be scraped giving a wrong read to such metric, I'm using a middleware to prevent this from happening:

```
func MonitorHandler() http.Handler {
	metricsHandler := promhttp.InstrumentMetricHandler(
		prometheus.DefaultRegisterer, promhttp.HandlerFor(prometheus.DefaultGatherer, promhttp.HandlerOpts{}),
	)
	return http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		if !MetricsSynced {
			w.WriteHeader(http.StatusInternalServerError)
			return
		}
		metricsHandler.ServeHTTP(w, r)
	})
}
```
 
is there a better approach? would be nice to include an example on this scenario

**Comment by beorn7** [comment]
Note that returning a 5xx on the metrics endpoint will make the whole target appear as "down" (i.e. `up==0`) from the Prometheus point of view. If the only task of your binary is to server those metrics (that you have to sync), i.e. if it is essentially an exporter, I would say you should only start serving any HTTP requests once you are done.

If you have other metrics to serve as well, how about registering the metrics only with the registry once you are done with sync'ing?

There are many ways, and the best one depends on your specific use case. I don't think there is an easy recipe we could document here in this repo. It could be done in some "best practice" entry on https://prometheus.io , but I doubt it's common enough to justify that. Most fundamentally, I'd say metrics should be designed to avoid persisted state. Prometheus is designed to handle things like counter resets, so for example you don't need to restore the state of counters but just start from zero again after a restart. The persistence should only happen in the TSDB of Prometheus.

Now I can imagine you have found a case where you need persistence anyway, but it will then be a niche case.

In different news, this kind of discussion fits way better onto the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users) rather than in a GitHub issue. I'm closing this one. Feel free to bring it to the mailing list if you want to discuss further and perhaps even find others with similar use cases.

**Comment by benitogf** [comment]
> Prometheus is designed to handle things like counter resets, so for example you don't need to restore the state of counters but just start from zero again after a restart

This makes sense, but having persistence outside of TSDB for the exporters allow more control on when the counters are restarted, e.g.

![image](https://user-images.githubusercontent.com/1633813/97518989-5f253580-19d3-11eb-9d1f-94e920d3943f.png)

even if the exporter application is restarted the counter will keep the value, I would guess that this is not such a niche use case since I have found it very useful on different monitoring situations

>  I would say you should only start serving any HTTP requests once you are done

Is there a response code that would achieve the same as not serving the request?

> In different news, this kind of discussion fits way better onto the prometheus-users mailing list rather than in a GitHub issue

I understand the need to keep the issues free of user support topics, but I feel that it could be achieved by using tags/labels? closing down a commonly used communication channel seems a bit unconstructive and unwelcoming 😟

**Comment by beorn7** [comment]
There are, sadly, many "commonly used" communication channels. We cannot serve all of them with the resources we have available. That's why we asks those that want to use those resources to use them in the way most feasible for those donating those resources. Not doing us that little favour seems unfriendly to me.

The mailing list, BTW, is also open to discussion about the choice of communication channels.
