### ISSUE TITLE
No way to clear/wipe/refresh metrics in tests with testutil before calling CollectAndCompare fucntion

### ISSUE THREAD

**Issue by BentCoder** [prometheus/client_golang#825]
Hi,

Is there any way to clear/wipe/refresh metrics (or any workaround) before calling `CollectAndCompare` for example? Current tests are failing because metrics are growing as I run tests.

Thanks

**Collector**
```go
var MyCounter = promauto.NewCounterVec(prometheus.CounterOpts{
	Namespace: "abc",
	Name:      "task_result",
	Help:      "Number of successful or failed tasks",
}, []string{"status" .....})
```

**Tests**
```go
fail := `
# HELP abc_task_result Number of successful or failed tasks
# TYPE abc_task_result counter
abc_task_result{status="failure" ...} 1
`

// This passes
testutil.CollectAndCompare(MyCounter, strings.NewReader(fail))

// I need to reset things here ...

succ := `
# HELP abc_task_result Number of successful or failed tasks
# TYPE abc_task_result counter
abc_task_result{status="success" ...} 1
`
// This fails because we still have the "task_result{status="failure" ...} 1" metric
testutil.CollectAndCompare(MyCounter, strings.NewReader(succ))
```

**Comment by st4nson** [comment]
Hi, `MyCounter.Reset()` should do the trick.

**Comment by stokito** [comment]
@st4nson I have some related questions: 
How can I reset **all** metrics from a registry?
Also how the metrics must be cleared and by whom? One day I'll get an overflow or some old metrics will eat all memory.
Now I thinking to add some job that will wipe out all metrics at midnight. For my app's admin it will be just fine to just get the raw /metrics and show it to see the whole picture for today. But a Prometheus will anyway collect data for historical analysis.
Is this a right solution? Because it looks like nobody doing this.
