### ISSUE TITLE
Feature: to add label when call ObserveDuration

### ISSUE THREAD

**Issue by xin-au** [prometheus/client_golang#830]
Hi all
Happy New Year!
Wondering is that possible to add or append a label when calling ObserveDuration.
For example, if we would like to measure the latency for different HTTP codes, and that code is only available after processing it.
Thanks!

**Comment by beorn7** [comment]
If I understand you correctly, that's precisely the use case described in this example: https://pkg.go.dev/github.com/prometheus/client_golang@v1.9.0/prometheus#example-Timer-Complex

In general, it makes more sense to ask questions like this on the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users) rather than in a GitHub issue. On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.
