### ISSUE TITLE
Conditional collecting based on HTTP header

### ISSUE THREAD

**Issue by muety** [prometheus/client_golang#837]
I'm happily using Prometheus for quite a while, however, I'm not too experienced with instrumenting applications. Also, my use case might be a bit special.

I have a multi-user "time-tracking" application and I want to offer every user the ability to retrieve their data as Prometheus metrics. For instance there will be, among others, a counter metric `myapp_seconds_total{project}`.

Now, is there a way to make my Prometheus collector dynamic in a way that it populates these metrics based on the currently logged in user? The user is identified through a `Bearer` token authorization header. Ideally, there would be some way to pass request parameters from `promhttp`'s handler down to the `Collect()` method.

Having the user name as an additional label (like `myapp_seconds_total{project, user}`) would be easy, however, that's not an option as user A is obviously not allowed to view metrics of user B.

This might not be exactly a use case Prometheus is made for, but is it still possible to realize the above scenario somehow?

**Comment by beorn7** [comment]
Broadly, you are asking for #135 . That issue also discusses "dynamic" collection as it is done in the [node exporter](https://github.com/prometheus/node_exporter).

You could follow a similar pattern as the node exporter, just using the bearer token instead of a URL parameter.

What you ask about passing parameters down the `Collect` method is a bit disputed, but I'm fairly certain that the next major version of this library will have a context parameter in the `Collect` method, see #228 (further down towards the end of the comments). However, that's a breaking change and cannot easily be added right now.

And even #135 will only happen in the next major version, if at all. (It's hard to come up with a way that is generic enough to cover all the use cases without being so tedious that it would be easier to do what the node exporter is doing already.)

In any case, I'll close this as the feature request is already tracked in two other issues.
