### ISSUE TITLE
Sorting, filtering and pagination via golang client

### ISSUE THREAD

**Issue by HelloWorld3031** [prometheus/client_golang#860]
Hi,

I'm new to this eco system. I have a simple question.
Using the golang client, could we send the queries which contain sorting, filtering and pagination params to the Prometheus server? or should we query the data as a whole and do these operations locally?

Thanks for your time.

**Comment by beorn7** [comment]
I'm pretty sure the API client doesn't support sorting, filtering, and pagination. But I'm not an expert for the API client, despite maintaining it. Perhaps @yeya24 as the most active recent contributor knows better or has opinions how to do this.

Generally, usage questions are best asked via the community channels rather than in a Github issue: https://prometheus.io/community/

**Comment by beorn7** [comment]
The lack of further comments here makes me believe that my response was more or less correct.

Also note that we have a long lasting discussion around where to place sorting (beyond the existing `sort` function): in PromQL, in a postprocessing step still run on the Prometheus server, or leave it to the caller? But as said, those discussions can be best followed via our [community channels](https://prometheus.io/community/).
