### ISSUE TITLE
Set values to counter for some use case

### ISSUE THREAD

**Issue by alok87** [prometheus/client_golang#872]
I have described my use case [here also.](https://stackoverflow.com/questions/67715773/usecase-needing-to-set-values-to-counter-in-prometheus-and-not-increment)

We are exposing a external system metric which is a counter as time series in Prometheus. The need is to analyze the increase in the metric in one day. 

Since the metric is always increasing value we want to use **Counter**.

**Problems**
1. The metric is available as the total value (`redshift_scan_query_total`) from external system. In the exporter, how do we set the total value using prometheus client? It allows only `Inc()` and `Add(d float64)`. I understand the functions are to prevent decrement in counter values.
2. The other issue is the external metric sometimes drops due to it being a approximate value and also due to some other factors. But we should not drop a counter from say 600 to 550, right ?

If **Gauge** is the correct metric for this usecase, then the problems with Gauge is when the exporter pod restarts, we get two time-series for each of the pod? Also, will `increase()` work with Gauge.

So I should continue to use **Counter**

Related https://github.com/prometheus/client_golang/issues/309

Please suggest.

**Comment by alok87** [comment]
Found https://www.robustperception.io/setting-a-prometheus-counter

**Comment by beorn7** [comment]
A counter must only drop if there has been a counter reset (not due to accuracy issues).

The definition of a timeseries (which is a separate one and which is the same) purely depends on labels, not on the type of the series.

Having said that, we use GH issues for bug reports and to track feature implementation. Please refer to the [community channels](https://prometheus.io/community/) to get support.
