### ISSUE TITLE
Error: type prometheus.Counter has no field or method AddWithExemplar

### ISSUE THREAD

**Issue by androna-xm** [prometheus/client_golang#889]
I have defined a counter 
```
var counterRequestLatency = promauto.NewCounter(prometheus.CounterOpts{
	Name: "request_latency_seconds_total",
	Help: "The total latency seconds of all the requests ",
})
```
and i am trying to use the `AddWithExemplar` method of the interface ExemplarAdder that Counter implements :
```
counterRequestLatency.AddWithExemplar(
			time.Since(start).Seconds() , prometheus.Labels{"traceID": traceID})
```

However i get this error 
`counterRequestLatency.AddWithExemplar undefined (type prometheus.Counter has no field or method AddWithExemplar)`

My go version go1.16.4 linux/amd64
Am i missing something?

**Comment by beorn7** [comment]
You have to do a type assertion: `counterRequestLatency.(prometheus.ExemplarAdder).AddWithExemplar(...)`

See also example here: https://github.com/prometheus/client_golang/blob/master/examples/random/main.go#L99

For usage questions, I recommend the community channels rather than GitHub issues, see here: https://prometheus.io/community/
