### ISSUE TITLE
Security Issues with Crypto and Text

### ISSUE THREAD

**Issue by nbeal** [prometheus/client_golang#894]
Older versions of golang.org/x/crypto and golang.org/x/text have security issues reported by CVE with proof of concept attacks.

[CVE-2020-9283 (crypto)](https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2020-9283)
[CVE-2020-14040 (text)](https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2020-14040)

Issue can be solved by removing the older version of these packages.

Crypto by making most up to date package >= golang.org/x/crypto@0.0.0-20201203163018-be400aefbc4c
Text by making most up to date package >= golang.org/x/text@0.3.3

**Comment by beorn7** [comment]
Neither of the vulnerabilities is relevant for this repo (doesn't use SSH, doesn't use UTF-16).

Nevertheless, we should update them with the next release, as per our usual procedure of getting dependencies up-to-date. This will organically happen with golang.org/x/text, but even after running the update procedure, golang.org/x/crypto is only updated to v0.0.0-20200622213623-75b288015ac9 . This means, even the newest versions of our dependencies don't require a newer version. Thus, the dependencies need to update their dependencies first.

About gogo/protobuf: This isn't used anymore. It's just in the dependency tree because of quirks of go modules. The code isn't really used.

**Comment by smuda** [comment]
I guess the circular dependency between client_golang and common requires multiple releases to get rid of vulnerable dependencies. For example, CVE-2020-14040 is detected in v1.11.0, even though it's really in v1.7.1 which is pulled in by common:

```
/github.com/prometheus/client_golang:v1.11.0 ->
/github.com/prometheus/common:v0.26.0 ->
/github.com/prometheus/client_golang:v1.7.1 ->
/github.com/prometheus/common:v0.10.0 ->
/golang.org/x/net:d28f0bde5980 ->
/golang.org/x/text:v0.3.0
```

**Comment by beorn7** [comment]
See https://github.com/prometheus/client_golang/issues/916#issuecomment-929330066 for an explanation why gogo/protobuf gets easily flagged by naive security scanners.

Interestingly, GitHub's Depandabot doesn't alert on any of the vulnerabilities listed in this issue. It seems to do something smart to find out if the vulnerability is actually relevant (or it's just not sensitive enough ;).
