### ISSUE TITLE
api.NewClient doesn't return error in case Address in the config struct is not reachable or does not exist

### ISSUE THREAD

**Issue by Kaitou786** [prometheus/client_golang#900]
When getting the client using the following code:
```
	cfg := prometheusapi.Config{
		Address: url,
	}
	client, err := prometheusapi.NewClient(cfg)
	if err != nil {
		return nil, err
	}
```	
In case the URL does not exist or not reachable the NewClient does not return any error

Using the:
```
github.com/prometheus/client_golang v1.11.0
github.com/prometheus/common v0.26.0
```

Expected Behaviour:
 When getting the client it should return the error if the address inside the config does not exist

Actual Behaviour:
nil error

Even when using this client to do `Client.Query` it doesn't return any error it returns nill for all `model.Value, Warnings, error`

**Comment by PhilipGough** [comment]
The `NewClient` function parses the user input to ensure it is a valid URL and returns and error otherwise. Passing a valid but unreachable URL to that function sounds like a user error.

Also running the example in https://github.com/prometheus/client_golang/blob/master/api/prometheus/v1/example_test.go#L30-L51, if I change it to an unreachable address I get a 404 from the `Query` function
