### ISSUE TITLE
Add secret to promhttp HandlerOpts 

### ISSUE THREAD

**Issue by yolossn** [prometheus/client_golang#936]
Often the metrics exposed can contain sensitive information and adding a secret to the handler directly will be very handy, prometheus supports `secrets` in scrape configs and it will be useful if the `promhttp` package also provides an easy way to secure the `promhttp` Handler.

**Comment by beorn7** [comment]
I think this shouldn't be handled specifically within the Prometheus metrics handler, but in a middleware or for the whole server so that it works more generally. https://github.com/prometheus/exporter-toolkit might be exactly what you are looking for.

As an example of using it, check out https://github.com/prometheus/collectd_exporter/blob/master/main.go .
